// <auto-generated />
namespace MVC4.MyOrganizer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewMDF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewMDF));
        
        string IMigrationMetadata.Id
        {
            get { return "201309180155195_NewMDF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
